### ISSUE TITLE
JOSS Review: anaconda install 

### ISSUE THREAD

**Issue by lheagy** [loftytopping/PyBox#8]
Originally from @highendcompute in openjournals/joss-reviews#755

NB on some systems, going anaconda route I got some issues, as highlighted in the README.md as likely need install sundials explicitly, which I did via
 conda install -c chemreac sundials blas
but still get

 [15:48:51] ~/tmp/PyBox$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from assimulo.solvers import RodasODE, CVode
Could not find  not found (required by /mnt/iusers01/pp01/mccssmb2/anaconda3/lib/python3.6/site-packages/assimulo/lib/radau5.cpython-36m-x86_64-linux-gnu.so)
Could not find  not found (required by /mnt/iusers01/pp01/mccssmb2/anaconda3/lib/python3.6/site-packages/assimulo/solvers/sundials.cpython-36m-x86_64-linux-gnu.so)
Could not find  not found (required by /mnt/iusers01/pp01/mccssmb2/anaconda3/lib/python3.6/site-packages/assimulo/solvers/kinsol.cpython-36m-x86_64-linux-gnu.so)
Could not find  not found (required by /mnt/iusers01/pp01/mccssmb2/anaconda3/lib/python3.6/site-packages/assimulo/lib/dopri5.cpython-36m-x86_64-linux-gnu.so)
Could not find  not found (required by /mnt/iusers01/pp01/mccssmb2/anaconda3/lib/python3.6/site-packages/assimulo/lib/rodas.cpython-36m-x86_64-linux-gnu.so)
Could not find  not found (required by /mnt/iusers01/pp01/mccssmb2/anaconda3/lib/python3.6/site-packages/assimulo/lib/odassl.cpython-36m-x86_64-linux-gnu.so)
Could not find ODEPACK functions
Could not find RADAR5
Could not find GLIMDA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RodasODE'

(This has happened on two systems where there was a system anaconda but it wasn't possible to use for obtaining new packages (since tried to install in system dir) so used the Anaconda script directly to install in $HOME/anaconda3 and set PATH to include this as first element

**Comment by loftytopping** [comment]
Many thanks for your time and effort on this @highendcompute. This is unfortunately a sympton of the Assimulo package. In response, Ive made the following changes:
- Urged caution in the README instructions, even with the conda build.
- Created an enhancement issue to not just rely on Assimulo in PyBox. After rigirous profiling and model testing re the ODE solvers, and especially after new developments, I will be able to make the decision on whether I can rely on Scipy libraries which would remove these issues. The Scipy libraries currently have the CVode solvers, and may include other stiff solvers in a future release. With regards to this, I will add a request that the Rodas methods are implemented. 

In addition, based on the above ethos, I have removed the default option to use OpenMP but leave this for a future version that has been fully profiled and optmised. This is also retained as an enhancement request and is duly noted in both the Python files and README.
